import { TABLE_DATA_BASE } from "../data/type";

// Mapping des champs vers des labels lisibles
export const fieldLabels: Record<string, string> = {
  //champs cacher
  id: "",
  _id: "",
  __v: "",
  idCashMovement: "",
  userId: "",
  reservationId: "",
  updatedAt: "",
  tripId: "",
  goodsId: "",
  password: "",
  //champs visible en francais
  createdAt: "Créé le",
  credit: "Crédit",
  debit: "Débit",
  tel: "Téléphone",
  email: "Email",
  role: "Rôle",
  type: "Type de mouvement",
  amountPaid: "Montant Payé",
  amountToPay: "Montant à Payer",
  paymentStatus: "Statut Paiement",
  clientAdresse: "Adresse Client",
  clientEmail: "Email Client",
  clientName: "Nom Client",
  clientPhone: "Téléphone Client",
  destAdresse: "Adresse Destinataire",
  destEmail: "Email Destinataire",
  destName: "Nom Destinataire",
  destTel: "Téléphone Destinataire",
  quantity: "Quantité",
  weight: "Poids (kg)",
  date: "Date",
  status: "Statut",
  itemName: "Nom du marchandise",
  itemPrice: "Prix Unitaire",
  totalPrice: "Prix Total",
  types: "Type de marchandise",
  boatId: "Bateau",
  depart: "Date de départ",
  arrive: "Date d'arrivée",
  from: "Lieu de départ",
  to: "Destination",
  embarkDate: "Date d'embarquement",
  unitWeight: "Poids Unitaire (kg)",
  totalWeight: "Poids Total (kg)",
  unitPrice: "Prix Unitaire",
  state: "Statut du voyage",
  numberLot: "Numéro de lot",
  name: "Nom",
  capacity: "Capacité (tonnes)",
  fuelType: "Type de carburant",
  fuelConsumed: "Carburant consommé (litres)",
  mileage: "Kilométrage (km)",
  maintenanceDate: "Date de maintenance",
  designation: "Désignation",
  crew: "Équipage",
};
export const collectionLabels: Record<string, string> = {
  Goods: "Marchandise",
  User: "Utilisateur",
  Role: "Rôle",
  Reservation: "Réservation",
  Trip: "Voyage",
  Boat: "Bateau",
  CashMovement: "Mouvement de caisse",
  FuelConsumption: "Consommation de carburant",
  CargoType: "Type de marchandise",
  Port: "Port",
  Notification: "Notification",
};
export const sideBarToloader: Record<string, string> = {
  merchandise: TABLE_DATA_BASE.GOODS,
  casing: TABLE_DATA_BASE.CASHMOVEMENT,
  boat: TABLE_DATA_BASE.BOAT,
  trajets: TABLE_DATA_BASE.TRIP,
  employe: TABLE_DATA_BASE.USER,
  profile: TABLE_DATA_BASE.USER,
  fueldManage: TABLE_DATA_BASE.FUELCONSUMPTION,
};
